# Generated by Django 3.2.4 on 2021-07-01 00:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('workouts', '0002_auto_20210630_1334'),
    ]

    operations = [
        migrations.RenameField(
            model_name='workout',
            old_name='target_muscles',
            new_name='target',
        ),
    ]
