# Generated by Django 3.2.4 on 2021-07-01 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workouts', '0003_rename_target_muscles_workout_target'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workout',
            name='target',
            field=models.CharField(max_length=200),
        ),
    ]
