# Generated by Django 3.2.4 on 2021-07-01 18:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('workouts', '0004_alter_workout_target'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workout',
            name='target',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='workouts.muscle'),
        ),
    ]
