# Generated by Django 3.2.4 on 2021-07-01 20:19

import autoslug.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('workouts', '0005_alter_workout_target'),
    ]

    operations = [
        migrations.AddField(
            model_name='muscle',
            name='slug',
            field=autoslug.fields.AutoSlugField(editable=False, null=True, populate_from='name'),
        ),
        migrations.AddField(
            model_name='workout',
            name='slug',
            field=autoslug.fields.AutoSlugField(editable=False, null=True, populate_from='name'),
        ),
    ]
