# Generated by Django 3.2.4 on 2021-07-01 20:24

import autoslug.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('workouts', '0006_auto_20210701_2019'),
    ]

    operations = [
        migrations.AlterField(
            model_name='muscle',
            name='slug',
            field=autoslug.fields.AutoSlugField(default='', editable=False, populate_from='name'),
        ),
        migrations.AlterField(
            model_name='workout',
            name='slug',
            field=autoslug.fields.AutoSlugField(default='', editable=False, populate_from='name'),
        ),
    ]
