# Generated by Django 3.2.4 on 2021-07-03 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workouts', '0008_workout_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='workout',
            name='video',
            field=models.CharField(default='', max_length=500),
        ),
    ]
