# Generated by Django 3.2.4 on 2021-07-22 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workouts', '0010_alter_workout_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='workout',
            name='equipment',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='workout',
            name='sets',
            field=models.CharField(default='', max_length=100),
        ),
    ]
